### ISSUE TITLE
docstr: plot_coords.py

### ISSUE THREAD

**Issue by jpolton** [NOC-MSM/pyBDY#111]
Add a doc string header to the ```plotting/plot_coords.py``` file.

I would include 

```
Benchmark data example usage:
 python plotting/plot_coords.py outputs/NNA_R12_bdyT_y1979m11.nc outputs/coordinates.bdy.nc 
````

**Comment by jdha** [comment]
I have an alternative view on the plotting routines (#111, #112, #113) - we can discuss at the meeting, but I would prefer a library/package of routines + command line access points and example notebooks.
